services:
    laravel.test:
        container_name: ip4y_app
        build:
            context: ./docker/8.3
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.3/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
    sql_server:
        container_name: ip4y_sql_server
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
            - '${DB_PORT:-1433}:1433'
        environment:
            MSSQL_SA_PASSWORD: '${DB_PASSWORD:-MyP@ssw0rd}'
            MSSQL_DATABASE: '${DB_DATABASE:-IP4Y}'
            MSSQL_TESTING_DATABASE: '${DB_TESTING_DATABASE:-IP4Y_TESTING}'
            ACCEPT_EULA: 'Y'
        volumes:
            - ./docker/volumes/sqlserver:/var/opt/mssql
            - ./docker/sqlserver-entrypoint:/usr/config
        networks:
            - sail
        # entrypoint: ["./usr/config/sqlserver-entrypoint.sh"]
networks:
    sail:
        driver: bridge